version: "3"

services:
    messageQ:
      image : rabbitmq:3-management
      container_name: rabbitmqManager
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=genericpass
      ports:
        - 15672:15672
        - 5672:5672
      restart: always